-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "rating" DECIMAL(3,2) NOT NULL DEFAULT 0.0,
ADD COLUMN     "reviewCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "soldCount" INTEGER NOT NULL DEFAULT 0;
